import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";
import Navbar from "@/components/Navbar";
import { Poppins, Orbitron, Roboto } from 'next/font/google';

const orbitron = Orbitron({
  subsets: ['latin'],
  variable: '--font-orbitron', // Important for Tailwind
});

const roboto = Roboto({
  subsets: ['latin'],
  weight: ["100" , "300" , "400" , "500" , "700" , "900"],
  variable: '--font-roboto', 
});

const poppins = Poppins({
  subsets: ['latin'], 
  weight: ["100" , "300" , "400" , "500" , "700" , "900"], 
  variable: '--font-poppins', 
});

export const metadata: Metadata = {
  title: "HypeXDev",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${orbitron.variable} ${roboto.variable} ${poppins.variable} antialiased dark:text-white dark:bg-[#0e081e]`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar/>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
